version: '3.1'

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - PORT=${PORT}
            - PASSPHRASE=${PASSPHRASE}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
#You can delete the commented lines if you are not using Langsmith tracing
#            - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
#            - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
#            - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
#            - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
