version: '3.1'

services:
    flowise:
        image: theanswerai/flowise:latest
        build:
            context: ..
        restart: always
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
            - DOMAIN=${DOMAIN}
            - AUTH0_JWKS_URI=${AUTH0_JWKS_URI}
            - AUTH0_SECRET=${AUTH0_SECRET}
            - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
            - AUTH0_BASE_URL=${AUTH0_BASE_URL}
            - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
            - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
            - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
            - AUTH0_SCOPE=${AUTH0_SCOPE}
            - AUTH0_TOKEN_SIGN_ALG=${AUTH0_TOKEN_SIGN_ALG}
            - AUTH0_ORGANIZATION_ID=${AUTH0_ORGANIZATION_ID}
            - MY_APP_VITE_AUTH_DOMAIN=${MY_APP_VITE_AUTH_DOMAIN}
            - MY_APP_VITE_AUTH_CLIENT_ID=${MY_APP_VITE_AUTH_CLIENT_ID}
            - MY_APP_VITE_AUTH_AUDIENCE=${MY_APP_VITE_AUTH_AUDIENCE}
            - MY_APP_VITE_AUTH_ORGANIZATION_ID=${MY_APP_VITE_AUTH_ORGANIZATION_ID}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        env_file:
            - .env
        #command: /bin/sh -c "sleep 3; yarn start"
